# Nixpacks Configuration for Elysia + Bun Application
# Este arquivo é opcional - Nixpacks detecta automaticamente Bun via bun.lock e package.json
# Mas pode ser usado para configurações customizadas

# Fase de instalação
[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

# Comando para iniciar a aplicação
# Nixpacks também usa automaticamente "bun run start" se o script estiver no package.json
[start]
cmd = "bun run start"

